### ISSUE TITLE
exceptions.ImportError: No module named ltc_scrypt

### ISSUE THREAD

**Issue by peterwillcn** [farsider350/p2pool-oneclick#6]
2023-02-05 05:36:50.343783 Initializing work...
Error while requesting best block header:
Traceback (most recent call last):
  File "/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/root/p2pool-dgb-scrypt/p2pool/util/deferral.py", line 41, in f
    result = yield func(*args, **kwargs)
  File "/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/root/p2pool-dgb-scrypt/p2pool/node.py", line 226, in poll_header
    handle_header((yield self.factory.conn.value.get_block_header(self.bitcoind_work.value['previous_block'])))
  File "/root/p2pool-dgb-scrypt/p2pool/node.py", line 208, in handle_header
    if not (self.net.PARENT.POW_FUNC(bitcoin_data.block_header_type.pack(new_header)) <= self.bitcoind_work.value['bits'].target):
  File "/root/p2pool-dgb-scrypt/p2pool/bitcoin/networks/digibyte.py", line 20, in <lambda>
    POW_FUNC = lambda data: pack.IntType(256).unpack(__import__('ltc_scrypt').getPoWHash(data))
exceptions.ImportError: No module named ltc_scrypt

**Comment by farsider350** [comment]
It seems you've installed the p2pool direct from its repo instead of using this installer.
In that case the following will fix.

cd digibyte_subsidy
sudo pypy setup.py install
cd ..
cd litecoin_scrypt
sudo pypy setup.py install
